In [2]:
import pandas as pd
import numpy as np
from codebase.file_utils import (
    save_obj,
    load_obj,
)
from codebase.plot import plot_density, plot_line, get_post_df
import altair as alt
from codebase.classes_data import Data
from codebase.ibis import exp_and_normalise
from run_smc2 import run_smc2
from codebase.file_utils import (
    save_obj,
    load_obj,
    make_folder,
    path_backslash
)
from codebase.ibis import post_process_sign
from pdb import set_trace


alt.data_transformers.disable_max_rows()


DataTransformerRegistry.enable('default')

In [3]:
log_dir1 = 'log/20210222_111136_mcmc/'
exp_data1 = load_obj( 'complete_data', log_dir1)
ps_mcmc = load_obj('mcmc_post_samples', log_dir1)


In [4]:
log_dir = 'log/20210222_124703_smc2test/'
exp_data = load_obj('data', log_dir)
t = load_obj('t', log_dir)
print(t)

166


##

In [5]:
particles = load_obj('particles', log_dir)
# particles.particles[5].particles['beta']

In [6]:
particles.extract_particles_in_numpy_array('alpha')

array([[-0.69370404,  0.13786902, -2.45045399, -1.10418113, -0.55214793,
        -2.22033304],
       [-0.25604091,  0.2124589 , -1.51820516, -0.74960642, -0.95272387,
        -1.91509146],
       [-0.36658577,  0.63308498, -2.1150854 , -1.07143893, -0.57198108,
        -1.83534119],
       ...,
       [-0.58548961,  0.22062775, -1.48311169, -1.15271455, -0.76532429,
        -2.06460541],
       [-0.5683487 ,  0.5207679 , -1.58112237, -0.91801966, -0.68119176,
        -2.01643033],
       [-0.64748163,  0.38561153, -1.74838945, -1.26642187, -0.9387671 ,
        -2.12585229]])

In [7]:
corrs = load_obj('jitter_corrs', log_dir)
corrs['beta']

array([0.00773201, 0.11646433, 0.17122298, 0.15886147, 0.        ,
       0.36633615, 0.        , 0.        , 0.21475484, 0.        ,
       0.        , 0.35666609, 0.37112171, 0.        , 0.        ,
       0.        , 0.38253354, 0.48105467, 0.        , 0.        ,
       0.        , 0.41108841, 0.43254931, 0.        , 0.        ,
       0.31026881, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.39794585, 0.        , 0.        , 0.        ,
       0.51998399, 0.        , 0.        , 0.        , 0.50780103,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.55054638, 0.        , 0.        , 0.        , 0.        ,
       0.57285554, 0.        , 0.        , 0.        , 0.        ,
       0.60482562, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.62788801, 0.        , 0.        , 0.        ,
       0.64061944, 0.        , 0.        , 0.46447354, 0.        ,
       0.59830261, 0.        , 0.        , 0.62159107, 0.     

In [8]:
particles.get_acceptance_rate_for_particle_m(0)[particles.get_threshold_ess_indicator()]

/home/konstantinos/myPhD/smc2/src/codebase/classes_smc2.py:82: RuntimeWarning: invalid value encountered in true_divide
  return (accs/trials)


array([1.        , 0.94736842, 0.72972973, 1.        , 0.91428571,
       0.44117647, 1.        , 1.        , 0.61290323, 0.76666667,
       0.93103448, 0.89285714, 0.88888889, 0.88461538, 0.72      ,
       0.66666667, 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 0.64705882, 0.875     , 0.93333333,
       1.        , 0.92307692, 1.        , 1.        , 1.        ,
       1.        , 0.875     , 0.85714286, 0.66666667, 1.        ,
       0.75      , 0.66666667, 1.        , 1.        ])

In [10]:
particles.get_acceptance_rate_for_particle_m(2)[particles.get_threshold_ess_indicator()]

array([1.        , 1.        , 0.97297297, 1.        , 0.97142857,
       0.55882353, 1.        , 1.        , 0.32258065, 0.96666667,
       0.68965517, 0.92857143, 0.59259259, 1.        , 1.        ,
       0.95833333, 0.95652174, 1.        , 0.95238095, 0.65      ,
       0.94736842, 1.        , 0.94117647, 0.9375    , 0.8       ,
       0.92857143, 1.        , 0.75      , 1.        , 0.9       ,
       1.        , 0.875     , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        ])

In [74]:
particles.get_threshold_ess_indicator()

array([False,  True,  True,  True, False,  True, False, False,  True,
       False, False,  True,  True, False, False, False,  True,  True,
       False, False, False,  True,  True, False, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False,  True, False,  True, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False,

In [75]:
particles.resample_particles_bundles()

# particles.gather_latent_variables_up_to_t(
#     t+1, 
#     exp_data.get_stan_data_upto_t(t+1)
# )

# particles.jitter_bundles_and_pick_one(exp_data.get_stan_data_upto_t(t + 1))
# particles.check_latent_particles_are_distinct()

# particles.jitter(exp_data.get_stan_data_upto_t(t + 1))

In [76]:
ps_smc2 = dict()
for name in particles.param_names:
    ps_smc2[name] = particles.extract_particles_in_numpy_array(name)


In [65]:
ps_smc2 = post_process_sign(ps_smc2)


## Plot

In [77]:
param = 'beta'
df = get_post_df(ps_smc2[param]) 
df['source'] = 'smc2'
plot_density(df, height=100)

alt.Chart(...)

In [78]:
param = 'alpha'
df = get_post_df(ps_smc2[param]) 
df['source'] = 'smc2'
plot_density(df, height=100)

alt.Chart(...)

## Plot MCMC samples

In [53]:
param = 'beta'
df = get_post_df(ps_smc2[param])
df_quant = df.groupby(['row', 'col'])[['value']].quantile(0.025).reset_index()
df_quant.rename({'value':'q1'}, axis=1, inplace=True)
df_quant2 = df.groupby(['row', 'col'])[['value']].quantile(0.975).reset_index()
df_quant2.rename({'value':'q2'}, axis=1, inplace=True)

df = df_quant.merge(df_quant2, on=['row', 'col'])

# simple quantile chart
df['source'] = 'smc2'
c1 = alt.Chart(df).mark_bar(opacity=0.6).encode(
        alt.X('q1', title=None),
        alt.X2('q2', title=None),
        alt.Row('row'),
        alt.Column('col'),
        alt.Color('source')
)
c1

alt.Chart(...)

In [54]:
df['index'] = 'r_' + df.row.astype(str)+'.c_'+df.col.astype(str)
df = df.loc[:,['index', 'q1', 'q2']]
df['source'] = 'smc2'
dd = pd.DataFrame(exp_data.raw_data['beta'], columns=['data'])
dd['col'] = 0
dd['row'] = np.arange(6)
dd['index'] = 'r_' + dd.row.astype(str)+'.c_'+dd.col.astype(str)
dd = dd.loc[:,['index', 'data']]
plot_data = df.merge(dd, on=['index'])

In [55]:
c1 = alt.Chart(plot_data).mark_bar(opacity=0.6).encode(
    alt.X('q1', title=None,  scale=alt.Scale(domain=[-2,2])),
    alt.X2('q2', title=None),
    alt.Color('source'),    
)
    

c2 = alt.Chart(plot_data).mark_point(opacity=1, color='red').encode(
        alt.X('data', title=None),
)
(c1+c2).facet(
       'index',
    columns=1
    )


alt.FacetChart(...)

In [37]:
load_obj('marg_lklhd', log_dir)

FileNotFoundError: [Errno 2] No such file or directory: 'log/20210222_124703_smc2test/marg_lklhd.p'