In [40]:
import pandas as pd
import numpy as np
from codebase.file_utils import (
    save_obj,
    load_obj,
)
from codebase.plot import plot_histogram, plot_density, plot_line, get_post_df
from codebase.ibis import post_process_sign, exp_and_normalise
import altair as alt
from codebase.classes_data import Data
from codebase.file_utils import (
    save_obj,
    load_obj,
    make_folder,
    path_backslash
)
from pdb import set_trace

alt.data_transformers.disable_max_rows()


DataTransformerRegistry.enable('default')

In [41]:
log_dir1 = 'log/20210301_110730_mcmc_debug//'
exp_data1 = load_obj( 'complete_data', log_dir1)
ps_mcmc = load_obj('mcmc_post_samples', log_dir1)
ps_mcmc = post_process_sign(ps_mcmc)

In [62]:
log_dir3 = 'log/20210301_110416_rash01//'
exp_data = load_obj('data', log_dir3)
t = load_obj('t', log_dir3)
print(t)
# particles.particles[5].particles['beta']

99


## Plot weighted histograms

In [74]:
particles = load_obj('particles', log_dir3)
ps_smc2 = dict()
for name in particles.param_names:
    ps_smc2[name] = particles.extract_particles_in_numpy_array(name)
particles.weights

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [75]:
particles.get_acceptance_rate_for_particle_m(0)

array([1.        , 0.97058824, 1.        , 0.625     , 0.93548387,
       1.        , 1.        , 1.        , 1.        , 0.92592593,
       0.40740741, 1.        , 1.        , 1.        , 1.        ,
       0.91666667, 0.82608696, 1.        , 1.        , 1.        ,
       0.95      , 1.        , 1.        , 0.55      , 1.        ,
       0.52631579, 0.78947368, 0.89473684, 1.        , 0.77777778,
       0.83333333, 0.88235294, 0.6875    , 0.75      , 0.9375    ,
       1.        , 0.86666667, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 0.92307692, 0.76923077,
       0.76923077, 0.84615385, 0.91666667, 0.83333333, 0.91666667,
       0.83333333, 1.        , 1.        , 0.72727273, 1.        ,
       0.8       , 1.        , 1.        , 1.        , 0.77777778,
       0.55555556, 0.88888889, 0.88888889, 1.        , 1.        ,
       1.        , 0.85714286, 0.85714286, 1.        , 1.        ,
       0.85714286, 0.85714286, 1.        , 1.        , 1.     

In [76]:
corrs = load_obj('jitter_corrs', log_dir3)
corrs

{'beta': array([ 0.24103111,  0.52552743,  0.61855748,  0.34348535,  0.51916139,
         0.65324046,  0.7766748 ,  0.        ,  0.69735524,  0.        ,
         0.62656826,  0.72317042,  0.        ,  0.78674036,  0.        ,
         0.25071721,  0.71846381,  0.        , -0.0230309 ,  0.80457266,
         0.        ,  0.        ,  0.        ,  0.        ,  0.59544427,
         0.        ,  0.        ,  0.7054416 ,  0.        ,  0.        ,
         0.77971695,  0.73657263,  0.        ,  0.        ,  0.81034141,
         0.        ,  0.        ,  0.        ,  0.        ,  0.82681046,
         0.        ,  0.77320404,  0.        ,  0.        ,  0.        ,
         0.        ,  0.86855906,  0.        ,  0.        ,  0.        ,
         0.8773596 ,  0.        ,  0.        ,  0.        ,  0.87661287,
         0.        ,  0.        ,  0.        ,  0.68100643,  0.        ,
         0.        ,  0.        ,  0.85323047,  0.        ,  0.        ,
         0.40733482,  0.        ,  0.      

In [77]:
for name in ['alpha', 'beta']:
    samples = np.squeeze(ps_smc2[name])
    w = exp_and_normalise(particles.weights)
    print('\n\nEstimate')
    print(np.round(np.average(samples,axis=0, weights=w),2))
    # print('\nRead Data')
    # print(np.round(exp_data.raw_data[name],2))



Estimate
[-0.53  0.33 -1.42 -1.3  -0.84 -1.99]


Estimate
[0.34 0.34 0.34 0.34 0.34 0.34]


In [78]:
particles.particles[1].particles['beta'].shape

(6, 1)

In [79]:
def get_histogram_data(ps_smc2, name):
    if name == 'alpha':
        plot_data = []
        for col in range(6):
            weights =  exp_and_normalise(particles.weights)
            hist, bin_edges = np.histogram(ps_smc2[name][:,col], weights = weights)
            center_bin_edges = bin_edges[1:] + ((bin_edges[1:] - bin_edges[:-1])/2.)
            plot_data_col = pd.DataFrame(hist, columns=['value'])
            plot_data_col['bin'] = center_bin_edges
            plot_data_col['col'] = col
            plot_data_col['row'] = 1
            plot_data.append(plot_data_col)
        return pd.concat(plot_data)
    if name=='beta':
        plot_data = []
        row = 0
        weights =  exp_and_normalise(particles.weights)
        hist, bin_edges = np.histogram(ps_smc2[name][:,row,0], weights = weights)
        center_bin_edges = bin_edges[1:] + ((bin_edges[1:] - bin_edges[:-1])/2.)

        plot_data_row = pd.DataFrame(hist, columns=['value'])
        plot_data_row['bin'] = center_bin_edges
        plot_data_row['row'] = row
        plot_data_row['col'] = 1
        plot_data.append(plot_data_row)
        return pd.concat(plot_data)
    

def plot_weighted_histogram(df, width=300, height=50) :
    # it only works for one chain for now
    c = alt.Chart(df).mark_bar(
        width = 10,
        ).encode(
        alt.X('bin:Q', title=None),
        alt.Y('value:Q'),
        alt.Row('row'),
        alt.Column('col'),
        alt.Color('source')
        ).resolve_scale(
            x='independent'
        ).properties(width=width, height=height)
    return c


In [80]:
pdata = get_histogram_data(ps_smc2, 'alpha')
pdata['source'] = 'smc2'

alpha_hist = plot_weighted_histogram(pdata, height=150, width = 300)
alpha_hist

alt.Chart(...)

In [81]:
pdata = get_histogram_data(ps_smc2, 'beta')
pdata['source'] = 'smc2'

beta_hist = plot_weighted_histogram(pdata)
beta_hist

alt.Chart(...)

In [71]:

t = load_obj('t', log_dir3)
particles = load_obj('particles', log_dir3)


In [72]:
particles.weights

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [73]:
particles.resample_particles_bundles()
ps_smc2 = dict()
for name in particles.param_names:
    ps_smc2[name] = particles.extract_particles_in_numpy_array(name)


##

## Or load existing directory

In [58]:
# log_dir = '/log/20210122_173348_mcmc_ibis_adapt9/'
# ps = load_obj( 'mcmc_post_samples', log_dir)
# ps['beta'] = ps['beta'][num_warmup:].copy()

In [82]:
ps_mcmc = post_process_sign(ps_mcmc)
ps_smc2 = post_process_sign(ps_smc2)


## Plot MCMC samples

In [83]:
param = 'beta'
df = get_post_df(ps_mcmc[param])
df = df[df.row==0]
df['source'] = 'mcmc'


df3 = get_post_df(ps_smc2[param]) 
df3= df3[df3.row==0]
df3['source'] = 'smc2'

plot_density(pd.concat([df, df3]), height=100).interactive()

alt.Chart(...)

In [84]:
param = 'alpha'
df = get_post_df(ps_mcmc[param]) 
df['source'] = 'mcmc'


df3 = get_post_df(ps_smc2[param]) 
df3['source'] = 'smc2'

plot_density(pd.concat([df, df3]), height=100) & alpha_hist.properties(height=100)



alt.VConcatChart(...)

## Plot quantiles

In [85]:
param = 'beta'
df = get_post_df(ps_smc2[param])
df_quant = df.groupby(['row', 'col'])[['value']].quantile(0.025).reset_index()
df_quant.rename({'value':'q1'}, axis=1, inplace=True)
df_quant2 = df.groupby(['row', 'col'])[['value']].quantile(0.975).reset_index()
df_quant2.rename({'value':'q2'}, axis=1, inplace=True)

df = df_quant.merge(df_quant2, on=['row', 'col'])

# simple quantile chart
df['source'] = 'smc2'
c1 = alt.Chart(df[df.row==0]).mark_bar(opacity=0.6).encode(
        alt.X('q1', title=None),
        alt.X2('q2', title=None),
        alt.Row('row'),
        alt.Column('col'),
        alt.Color('source')
)
c1

alt.Chart(...)

## chart overlaying quantiles with real data

In [86]:
df['index'] = 'r_' + df.row.astype(str)+'.c_'+df.col.astype(str)
df = df.loc[:,['index', 'q1', 'q2']]
df['source'] = 'smc2'
dd = pd.DataFrame(exp_data1.raw_data['beta'], columns=['data'])
dd['col'] = 0
dd['row'] = np.arange(6)
dd['index'] = 'r_' + dd.row.astype(str)+'.c_'+dd.col.astype(str)
dd = dd.loc[:,['index', 'data']]
plot_data = df.merge(dd, on=['index'])

In [87]:
plot_data = plot_data[plot_data['index']=='r_0.c_0']

c1 = alt.Chart(plot_data).mark_bar(opacity=0.6).encode(
    alt.X('q1', title=None,  scale=alt.Scale(domain=[-2,2])),
    alt.X2('q2', title=None),
    alt.Color('source'),    
)
    

c2 = alt.Chart(plot_data).mark_point(opacity=1, color='red').encode(
        alt.X('data', title=None),
)
(c1+c2).facet(
       'index',
    columns=1
    )


alt.FacetChart(...)

## chart overlaying quantiles with real data

In [24]:
param = 'alpha'
df = get_post_df(ps_smc2[param])
df_quant = df.groupby(['row', 'col'])[['value']].quantile(0.025).reset_index()
df_quant.rename({'value':'q1'}, axis=1, inplace=True)
df_quant2 = df.groupby(['row', 'col'])[['value']].quantile(0.975).reset_index()
df_quant2.rename({'value':'q2'}, axis=1, inplace=True)

df = df_quant.merge(df_quant2, on=['row', 'col'])

# simple quantile chart
df['source'] = 'smc2'
c1 = alt.Chart(df).mark_bar(opacity=0.6).encode(
        alt.X('q1', title=None),
        alt.X2('q2', title=None),
        alt.Row('row'),
        alt.Column('col'),
        alt.Color('source')
)
c1

alt.Chart(...)

In [25]:
df['index'] = 'r_' + df.row.astype(str)+'.c_'+df.col.astype(str)
df = df.loc[:,['index', 'q1', 'q2']]
df['source'] = 'smc2'
dd = pd.DataFrame(exp_data1.raw_data['alpha'], columns=['data'])
dd['col'] = np.arange(6)
dd['row'] = 0
dd['index'] = 'r_' + dd.row.astype(str)+'.c_'+dd.col.astype(str)
dd = dd.loc[:,['index', 'data']]
plot_data = df.merge(dd, on=['index'])

In [26]:
c1 = alt.Chart(plot_data).mark_bar(opacity=0.6).encode(
    alt.X('q1', title=None,  scale=alt.Scale(domain=[-3,3])),
    alt.X2('q2', title=None),
    alt.Color('source'),    
)
    

c2 = alt.Chart(plot_data).mark_point(opacity=1, color='red').encode(
        alt.X('data', title=None),
)
(c1+c2).facet(
       'index',
    columns=1
    )


alt.FacetChart(...)