## Numpy arrays equal return pointers

In [139]:
a = np.ones(5)
b = a
b

array([1., 1., 1., 1., 1.])

In [140]:
a[0] = 2
b

array([2., 1., 1., 1., 1.])

In [141]:
a = np.ones(5)
b = a.copy()
a[0] = 2
b

array([1., 1., 1., 1., 1.])

## Test with objects

In [116]:
import numpy as np
class Order:
    def __init__(
        self,
        name,
        item
    ):
        self.name = name
        self.item = item
    
    def kitchen_copy(self):
        # returns a pointer to the original item
        self.kitchen_copy = self.item
    
    def kitchen_copy2(self):
        # makes a new copy of the item
        self.kitchen_copy = self.item.copy()
    
    def update_item(self, new_item):
        self.item[0] = new_item
        
    def check_kitchen_copy(self):
        return self.kitchen_copy
    
        

In [123]:
myorder = Order('Kon', np.array(['fries','coke']))

In [124]:
myorder.kitchen_copy()

In [125]:
myorder.check_kitchen_copy()

array(['fries', 'coke'], dtype='<U5')

In [126]:
myorder.update_item('burger')

In [127]:
myorder.check_kitchen_copy() # returns the updated value

array(['burge', 'coke'], dtype='<U5')

In [132]:
myorder = Order('Kon', np.array(['fries','coke']))

In [133]:
myorder.kitchen_copy2()

In [134]:
myorder.check_kitchen_copy()

array(['fries', 'coke'], dtype='<U5')

In [135]:
myorder.update_item('burger')

In [137]:
myorder.check_kitchen_copy() # copy is not updated yet

array(['fries', 'coke'], dtype='<U5')

In [138]:
myorder.kitchen_copy2()
myorder.check_kitchen_copy() # copy is only now updated

array(['burge', 'coke'], dtype='<U5')

## Test np.copy

In [2]:
import numpy as np

a = np.ones(3)
b = np.copy(a)

In [4]:
a = a*3
a

array([3., 3., 3.])

In [5]:
b

array([1., 1., 1.])

In [6]:
a = np.arange(3)
a

array([0, 1, 2])

In [8]:
np.unique(a)

array([0, 1, 2])

In [15]:
dim = list(a.shape)
dim.insert(0, 1)
tuple(dim)

(1, 3)